# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-22 15:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClubName', models.CharField(blank='True', max_length=50)),
                ('ClubDescription', models.TextField(blank='True', max_length=500)),
                ('ClubManager', models.TextField(blank='True')),
                ('ClubMemberSum', models.IntegerField(blank='True')),
                ('ClubMember', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
