# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-22 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_clublist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clublist',
            old_name='ClubManager',
            new_name='ClubManager1',
        ),
        migrations.AddField(
            model_name='clublist',
            name='ClubManager2',
            field=models.TextField(blank='True'),
        ),
    ]
